// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.auth.security.stub;

public final class Auth {
  private Auth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthenticationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthenticationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AuthenticationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AuthenticationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RegistrationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RegistrationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_token_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_token_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogoutResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TokenValidationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TokenValidationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserDetails_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UserDetails_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RefreshTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RefreshTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RefreshTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RefreshTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nauth.proto\"8\n\025AuthenticationRequest\022\r\n" +
      "\005email\030\001 \001(\t\022\020\n\010password\030\002 \001(\t\"E\n\026Authen" +
      "ticationResponse\022\024\n\014access_token\030\001 \001(\t\022\025" +
      "\n\rrefresh_token\030\002 \001(\t\"1\n\023RegistrationReq" +
      "uest\022\032\n\004user\030\001 \001(\0132\014.UserRequest\"\'\n\024Regi" +
      "strationResponse\022\017\n\007message\030\001 \001(\t\"\r\n\013Dat" +
      "aRequest\"f\n\004User\022\n\n\002id\030\001 \001(\003\022\021\n\tfirstnam" +
      "e\030\002 \001(\t\022\020\n\010lastname\030\003 \001(\t\022\r\n\005email\030\004 \001(\t" +
      "\022\020\n\010password\030\005 \001(\t\022\014\n\004role\030\006 \001(\t\"a\n\013User" +
      "Request\022\021\n\tfirstname\030\001 \001(\t\022\020\n\010lastname\030\002" +
      " \001(\t\022\r\n\005email\030\003 \001(\t\022\020\n\010password\030\004 \001(\t\022\014\n" +
      "\004role\030\005 \001(\t\"l\n\005token\022\n\n\002id\030\001 \001(\003\022\r\n\005toke" +
      "n\030\002 \001(\t\022\021\n\ttokenType\030\003 \001(\t\022\017\n\007revoked\030\004 " +
      "\001(\t\022\017\n\007expired\030\005 \001(\t\022\023\n\004user\030\006 \001(\0132\005.Use" +
      "r\"\035\n\014TokenRequest\022\r\n\005token\030\001 \001(\t\"!\n\016Logo" +
      "utResponse\022\017\n\007success\030\001 \001(\010\"6\n\027TokenVali" +
      "dationResponse\022\r\n\005valid\030\001 \001(\010\022\014\n\004role\030\002 " +
      "\001(\t\"\237\001\n\013UserDetails\022\020\n\010username\030\001 \001(\t\022\023\n" +
      "\013authorities\030\002 \003(\t\022\033\n\023account_non_expire" +
      "d\030\003 \001(\010\022\032\n\022account_non_locked\030\004 \001(\010\022\037\n\027c" +
      "redentials_non_expired\030\005 \001(\010\022\017\n\007enabled\030" +
      "\006 \001(\010\",\n\023RefreshTokenRequest\022\025\n\rrefresh_" +
      "token\030\001 \001(\t\",\n\024RefreshTokenResponse\022\024\n\014a" +
      "ccess_token\030\001 \001(\t2j\n\013UserService\022\"\n\013getU" +
      "serInfo\022\014.DataRequest\032\005.User\0227\n\010Register" +
      "\022\024.RegistrationRequest\032\025.RegistrationRes" +
      "ponse2\361\001\n\013AuthService\022?\n\014Authenticate\022\026." +
      "AuthenticationRequest\032\027.AuthenticationRe" +
      "sponse\0228\n\rValidateToken\022\r.TokenRequest\032\030" +
      ".TokenValidationResponse\022(\n\006Logout\022\r.Tok" +
      "enRequest\032\017.LogoutResponse\022=\n\014RefreshTok" +
      "en\022\024.RefreshTokenRequest\032\027.Authenticatio" +
      "nResponseB\032\n\026com.auth.security.stubP\001b\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_AuthenticationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AuthenticationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthenticationRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_AuthenticationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AuthenticationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AuthenticationResponse_descriptor,
        new java.lang.String[] { "AccessToken", "RefreshToken", });
    internal_static_RegistrationRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_RegistrationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationRequest_descriptor,
        new java.lang.String[] { "User", });
    internal_static_RegistrationResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_RegistrationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RegistrationResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_DataRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataRequest_descriptor,
        new java.lang.String[] { });
    internal_static_User_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_User_descriptor,
        new java.lang.String[] { "Id", "Firstname", "Lastname", "Email", "Password", "Role", });
    internal_static_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserRequest_descriptor,
        new java.lang.String[] { "Firstname", "Lastname", "Email", "Password", "Role", });
    internal_static_token_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_token_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_token_descriptor,
        new java.lang.String[] { "Id", "Token", "TokenType", "Revoked", "Expired", "User", });
    internal_static_TokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_TokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenRequest_descriptor,
        new java.lang.String[] { "Token", });
    internal_static_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogoutResponse_descriptor,
        new java.lang.String[] { "Success", });
    internal_static_TokenValidationResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_TokenValidationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TokenValidationResponse_descriptor,
        new java.lang.String[] { "Valid", "Role", });
    internal_static_UserDetails_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_UserDetails_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UserDetails_descriptor,
        new java.lang.String[] { "Username", "Authorities", "AccountNonExpired", "AccountNonLocked", "CredentialsNonExpired", "Enabled", });
    internal_static_RefreshTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_RefreshTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RefreshTokenRequest_descriptor,
        new java.lang.String[] { "RefreshToken", });
    internal_static_RefreshTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_RefreshTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RefreshTokenResponse_descriptor,
        new java.lang.String[] { "AccessToken", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
