// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.auth.security.stub;

public interface DataRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DataRequest)
    com.google.protobuf.MessageOrBuilder {
}
