// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.auth.security.stub;

public interface RefreshTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RefreshTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string refresh_token = 1;</code>
   * @return The refreshToken.
   */
  java.lang.String getRefreshToken();
  /**
   * <code>string refresh_token = 1;</code>
   * @return The bytes for refreshToken.
   */
  com.google.protobuf.ByteString
      getRefreshTokenBytes();
}
