// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.auth.security.stub;

public interface RegistrationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RegistrationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.UserRequest user = 1;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.UserRequest user = 1;</code>
   * @return The user.
   */
  com.auth.security.stub.UserRequest getUser();
  /**
   * <code>.UserRequest user = 1;</code>
   */
  com.auth.security.stub.UserRequestOrBuilder getUserOrBuilder();
}
