// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: auth.proto

package com.auth.security.stub;

public interface tokenOrBuilder extends
    // @@protoc_insertion_point(interface_extends:token)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string token = 2;</code>
   * @return The token.
   */
  java.lang.String getToken();
  /**
   * <code>string token = 2;</code>
   * @return The bytes for token.
   */
  com.google.protobuf.ByteString
      getTokenBytes();

  /**
   * <code>string tokenType = 3;</code>
   * @return The tokenType.
   */
  java.lang.String getTokenType();
  /**
   * <code>string tokenType = 3;</code>
   * @return The bytes for tokenType.
   */
  com.google.protobuf.ByteString
      getTokenTypeBytes();

  /**
   * <code>string revoked = 4;</code>
   * @return The revoked.
   */
  java.lang.String getRevoked();
  /**
   * <code>string revoked = 4;</code>
   * @return The bytes for revoked.
   */
  com.google.protobuf.ByteString
      getRevokedBytes();

  /**
   * <code>string expired = 5;</code>
   * @return The expired.
   */
  java.lang.String getExpired();
  /**
   * <code>string expired = 5;</code>
   * @return The bytes for expired.
   */
  com.google.protobuf.ByteString
      getExpiredBytes();

  /**
   * <code>.User user = 6;</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.User user = 6;</code>
   * @return The user.
   */
  com.auth.security.stub.User getUser();
  /**
   * <code>.User user = 6;</code>
   */
  com.auth.security.stub.UserOrBuilder getUserOrBuilder();
}
