eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8013
spring:
  application:
    name: compteur-grpcclient
grpc:
  client:
    CompteurService:
      address : static://localhost:9986
      negotiation-type: plaintext

management:
  tracing:
    sampling:
      probability: 1.0
