eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8021
spring:
  application:
    name: consommation-grpcclient
grpc:
  client:
    ConsommationService:
      address : static://localhost:9985
      negotiation-type: plaintext

management:
  tracing:
    sampling:
      probability: 1.0
