eureka:
  client:
    #register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        #- id: local
          #uri: lb://local-grpc-client
          #predicates:
         #   - Path=/api/v1/local/**
          #filters:
          #  - AuthenticationFilter=ADMIN
         # filters:
         #   - name: AuthenticationFilter
          #    args:
          #      role: USER
        - id: schools
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/schools/**
          #filters:
           # - AuthenticationFilter=ADMIN
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: districts
          uri: http://localhost:8011
          predicates:
            - Path=/api/v1/district/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
                #roles:
                #  - ADMIN
                #  - USER
        - id: regions
          uri: http://localhost:8011
          predicates:
            - Path=/api/v1/region/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: natureExercises
          uri: http://localhost:8011
          predicates:
            - Path=/api/v1/natureExercise/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: typeLocaux
          uri: http://localhost:8011
          predicates:
            - Path=/api/v1/typeLocal/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: local
          uri: http://localhost:8011
          predicates:
            - Path=/api/v1/local/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: compteur
          uri: http://localhost:8013
          predicates:
            - Path=/api/v1/compteur/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: bordereau
          uri: http://localhost:8021
          predicates:
            - Path=/api/v1/bordereau/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: consommation
          uri: http://localhost:8021
          predicates:
            - Path=/api/v1/consommation/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: statistic
          uri: http://localhost:8060
          predicates:
            - Path=/api/v1/statistique/**
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: report
          uri: http://localhost:8060
          predicates:
              - Path=/api/v1/reports/**
          #filters:
          #  - AuthenticationFilter=USER
          filters:
            - name: AuthenticationFilter
              args:
                role: ADMIN
        - id: security
          uri: http://localhost:8099
          predicates:
            - Path=/api/v1/auth/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://127.0.0.1:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS

management:
  tracing:
    sampling:
      probability: 1.0
