eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8060
spring:
  application:
    name: report
grpc:
  client:
    schoolService:
      address : static://localhost:9898
      negotiation-type: plaintext

management:
  tracing:
    sampling:
      probability: 1.0
